version: '3'

services:
  database:
    image: mysql:8.0
    # cap_add:
    #   - SYS_NICE
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./var/docker/db/data:/var/lib/mysql:rw
  # redis:
  #   image: redis/redis-stack-server:6.2.2-v1
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - ./var/docker/redis/data:/data:rw
  #   environment:
  #     REDIS_ARGS: --requirepass ${REDIS_PASSWORD:-redis-stack-password}
  php-fpm:
    build: ./docker/php-fpm
    volumes:
      - ./:/app
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./:/app
      - ./var/log/nginx:/var/log/nginx
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php-fpm
    working_dir: /app
